### PR TITLE
NEL reports are not observable

### PR DESCRIPTION
**Pull request by dcreager**
State this explicitly (even though it's the default), and add a note explaining why, to help ensure that we don't accidentally remove this restriction in the future.

### CODE REVIEW

**Comment by sleevi** [comment]
I have trouble convincing myself that we actually have this property today. I think it's good to document intent, but I'm hesitant to accept the statement that we achieve that intent.

**Comment by dcreager** [comment]
Do you mean that you think NEL reports might currently be observable in Chrome?  I think the ReportingObserver code that Paul wrote only lives in Blink, and isn't plumbed down to the network stack where NEL reports are created.  @paulmeyer90, do I have that right?

I have a [pending CL](https://chromium-review.googlesource.com/c/chromium/src/+/1106518) that adds some WPT tests for NEL; I'll add one that verifies that they're not observable.

**Comment by sleevi** [comment]
@dcreager Right, I think stating "They are not observable" specifies an end-state that may not be true, but stating "They must not be observable" states a security property that must be upheld.

As an example of areas that I think lack having a formal analysis:
* A compression scheme at the HTTP layer could end up leaking context or contents in a way that is network observable (think of things like the [CRIME](https://en.wikipedia.org/wiki/CRIME) or [BREACH](https://en.wikipedia.org/wiki/BREACH) attacks)
* Things that are Network Observable may end up being Script Observable, especially as we continue to introduce new networking capabilities.
  * For example, if the 3P had a series of connections going to the reporting endpoint, can they observe that a report is sent or not sent for a given host by looking at things like effective bandwidth or congestion windows.

This isn't stating that I know some attack against this - rather, I'm uncertain that we can absolutely say "X is not possible", but I'm fully onboard with stating "X MUST NOT be possible" as the objective, so that conforming implementations do take the time to examine and consider holistically those properties, and that security researchers know boundaries from hubris ;)

**Comment by dcreager** [comment]
Ah, I think I see what you're saying.  (And I agree with all of it!)  I was trying to say something slightly more precise / limited — that if a NEL implementation generates a report to upload to a collector, that report is not visible to any JavaScript `ReportingObserver`s that you've registered.  Let me take another stab at the note to clarify that and also mention some of the points you raised.

**Comment by dcreager** [comment]
It might also be worth updating Reporting, which is what defines "observable from JavaScript" to mean "reports will not be seen by ReportingObservers"

**Comment by dcreager** [comment]
PTAL; this depends on w3c/reporting#101, which changes it from "observable from JavaScript" → "visible to ReportingObservers"

**Pull request merged**
